Zipkin integration for the HTTP dispatcher
projectriff-archive/function-sidecar pull request #39
Opened 2018-01-02 19:00 UTC by freynca

Zipkin integration for the HTTP dispatcher: https://github.com/projectriff/function-sidecar/issues/3

2018-01-02 19:00 UTC, pivotal-issuemaster commented
@freynca Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=projectriff/function-sidecar&pullRequestId=39)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=projectriff/function-sidecar&pullRequestId=39) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2018-01-04 14:20 UTC, ericbottard requested changes
This should be rebased on top of latest master.
The following comment also applies to the http-gw PR: is openzipkin/zipkin-go-opentracing the right approach? Why not openzipkin/zipkin-go ? Also, shouldn't we strive for an integration that covers all protocols at the sidecar level? What do we gain by using http specific embedding here, as a function implementor is not likely to interact with zipkin (even though the http server part (eg node invoker) could, what do we get really? The invocation is on localhost). I don't claim to have answers to these questions, but I think this should be discussed before we go head on with an implementation path.

Also, why http collection? why not kafka collection?
Once this is rebased on master, please provide instructions on how to test this end to end, if you have them

2018-01-04 14:20 UTC, ericbottard commented on pkg/tracing/trace_context.go
> +	InitRequestSpan(r *http.Request) (FinishableSpan, error)
I'm not sure I see where these abstractions lead us to, as it actually is http specific given this function signature

2018-01-04 14:20 UTC, ericbottard commented on pkg/tracing/trace_context.go
> +	return span, c.Tracer.Inject(span.Context(), opentracing.TextMap, opentracing.HTTPHeadersCarrier(r.Header))
As for the http-gw PR, even though it is less obvious, isn't there a way this could be achieved by wrapping the http.Client in a decorator?

2018-02-05 15:49 UTC, ericbottard commented
Closing, will revisit later

2018-02-05 15:49 UTC, closed without merging